//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace top_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_subscibers
    {
        public long id { get; set; }
        public long owner_id { get; set; }
        public long subscriber_id { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
